---
name: build

on:
  push:
    branches: ["main"]
    tags: ["v*"]
    paths:
      - .github/workflows/*.yml
      - "**/*.go"
      - go.*
      - Dockerfile
      - .golangci.yaml
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/*.yml
      - "**/*.go"
      - go.*
      - Dockerfile
      - Makefile
      - .golangci.yaml

jobs:
  security:
    if: ${{ github.event.head_commit.message != '.' }}
    uses: andreygrechin/github-actions/.github/workflows/security-scans.yml@main

  lint:
    permissions:
      contents: read
      pull-requests: read
    if: ${{ github.event.head_commit.message != '.' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23.x"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: go vet
        run: go vet ./...

      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          install-go: false
          version: latest

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4
          args: --show-stats

  build:
    if: ${{ github.event.head_commit.message != '.' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23.x"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go get .

      - name: Build
        run: |
          make build

      - name: Test
        run: go test -coverprofile=coverage.txt -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
