---
name: gitleaks

on:
  pull_request:
  push:
    branches: ["main"]
  schedule:
    - cron: 45 21 * * FRI

permissions:
  contents: read

jobs:
  gitleaks:
    if: github.event.head_commit.message != '.'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
