---
name: Security Scan

on:
  push:
    paths:
      - ".github/workflows/*.yml"
      - "**/*.go"
      - "go.*"
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - "**/*.go"
      - "go.*"
  schedule:
    - cron: 0 3 * * FRI

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23.x"]
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - id: govulncheck
        uses: golang/govulncheck-action@v1
